//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KKN_UI.KKN_Demo_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KKN_Demo_ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceResultNoValue))]
    public partial class KKN_Demo_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDemoByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDemoJoinByDemoIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDemoByDetailIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KKN_Demo_Service() {
            this.Url = global::KKN_UI.Properties.Settings.Default.KKN_UI_KKN_Demo_Service_KKN_Demo_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDemoByIdCompletedEventHandler GetDemoByIdCompleted;
        
        /// <remarks/>
        public event SaveDemoCompletedEventHandler SaveDemoCompleted;
        
        /// <remarks/>
        public event SaveDeleteCompletedEventHandler SaveDeleteCompleted;
        
        /// <remarks/>
        public event GetDemoJoinByDemoIdCompletedEventHandler GetDemoJoinByDemoIdCompleted;
        
        /// <remarks/>
        public event GetDemoByDetailIdCompletedEventHandler GetDemoByDetailIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemoById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult GetDemoById(int id) {
            object[] results = this.Invoke("GetDemoById", new object[] {
                        id});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDemoByIdAsync(int id) {
            this.GetDemoByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDemoByIdAsync(int id, object userState) {
            if ((this.GetDemoByIdOperationCompleted == null)) {
                this.GetDemoByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemoByIdOperationCompleted);
            }
            this.InvokeAsync("GetDemoById", new object[] {
                        id}, this.GetDemoByIdOperationCompleted, userState);
        }
        
        private void OnGetDemoByIdOperationCompleted(object arg) {
            if ((this.GetDemoByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemoByIdCompleted(this, new GetDemoByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveDemo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult SaveDemo(DemoView model) {
            object[] results = this.Invoke("SaveDemo", new object[] {
                        model});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDemoAsync(DemoView model) {
            this.SaveDemoAsync(model, null);
        }
        
        /// <remarks/>
        public void SaveDemoAsync(DemoView model, object userState) {
            if ((this.SaveDemoOperationCompleted == null)) {
                this.SaveDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDemoOperationCompleted);
            }
            this.InvokeAsync("SaveDemo", new object[] {
                        model}, this.SaveDemoOperationCompleted, userState);
        }
        
        private void OnSaveDemoOperationCompleted(object arg) {
            if ((this.SaveDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDemoCompleted(this, new SaveDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult SaveDelete(int id, int userId) {
            object[] results = this.Invoke("SaveDelete", new object[] {
                        id,
                        userId});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveDeleteAsync(int id, int userId) {
            this.SaveDeleteAsync(id, userId, null);
        }
        
        /// <remarks/>
        public void SaveDeleteAsync(int id, int userId, object userState) {
            if ((this.SaveDeleteOperationCompleted == null)) {
                this.SaveDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDeleteOperationCompleted);
            }
            this.InvokeAsync("SaveDelete", new object[] {
                        id,
                        userId}, this.SaveDeleteOperationCompleted, userState);
        }
        
        private void OnSaveDeleteOperationCompleted(object arg) {
            if ((this.SaveDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDeleteCompleted(this, new SaveDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemoJoinByDemoId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult GetDemoJoinByDemoId(int demoId) {
            object[] results = this.Invoke("GetDemoJoinByDemoId", new object[] {
                        demoId});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDemoJoinByDemoIdAsync(int demoId) {
            this.GetDemoJoinByDemoIdAsync(demoId, null);
        }
        
        /// <remarks/>
        public void GetDemoJoinByDemoIdAsync(int demoId, object userState) {
            if ((this.GetDemoJoinByDemoIdOperationCompleted == null)) {
                this.GetDemoJoinByDemoIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemoJoinByDemoIdOperationCompleted);
            }
            this.InvokeAsync("GetDemoJoinByDemoId", new object[] {
                        demoId}, this.GetDemoJoinByDemoIdOperationCompleted, userState);
        }
        
        private void OnGetDemoJoinByDemoIdOperationCompleted(object arg) {
            if ((this.GetDemoJoinByDemoIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemoJoinByDemoIdCompleted(this, new GetDemoJoinByDemoIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDemoByDetailId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult GetDemoByDetailId(int id) {
            object[] results = this.Invoke("GetDemoByDetailId", new object[] {
                        id});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDemoByDetailIdAsync(int id) {
            this.GetDemoByDetailIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDemoByDetailIdAsync(int id, object userState) {
            if ((this.GetDemoByDetailIdOperationCompleted == null)) {
                this.GetDemoByDetailIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemoByDetailIdOperationCompleted);
            }
            this.InvokeAsync("GetDemoByDetailId", new object[] {
                        id}, this.GetDemoByDetailIdOperationCompleted, userState);
        }
        
        private void OnGetDemoByDetailIdOperationCompleted(object arg) {
            if ((this.GetDemoByDetailIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemoByDetailIdCompleted(this, new GetDemoByDetailIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResult {
        
        private int codeField;
        
        private int errorLogIdField;
        
        private string[] messagesField;
        
        private object dataField;
        
        private bool isSuccessField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int errorLogId {
            get {
                return this.errorLogIdField;
            }
            set {
                this.errorLogIdField = value;
            }
        }
        
        /// <remarks/>
        public string[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public object data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IDNAME {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DemoView {
        
        private int idField;
        
        private string demoStringField;
        
        private int demoIntField;
        
        private System.Nullable<int> demoIntNullableField;
        
        private System.DateTime demoDateField;
        
        private System.Nullable<System.DateTime> demoDateNullableField;
        
        private decimal demoDecimalField;
        
        private System.Nullable<decimal> demoDecimalNullableField;
        
        private bool demoBooleanField;
        
        private System.Nullable<bool> demoBooleanNullableField;
        
        private int isActiveField;
        
        private int userActionField;
        
        private IDNAME[] demoJoinsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DemoString {
            get {
                return this.demoStringField;
            }
            set {
                this.demoStringField = value;
            }
        }
        
        /// <remarks/>
        public int DemoInt {
            get {
                return this.demoIntField;
            }
            set {
                this.demoIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DemoIntNullable {
            get {
                return this.demoIntNullableField;
            }
            set {
                this.demoIntNullableField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DemoDate {
            get {
                return this.demoDateField;
            }
            set {
                this.demoDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DemoDateNullable {
            get {
                return this.demoDateNullableField;
            }
            set {
                this.demoDateNullableField = value;
            }
        }
        
        /// <remarks/>
        public decimal DemoDecimal {
            get {
                return this.demoDecimalField;
            }
            set {
                this.demoDecimalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DemoDecimalNullable {
            get {
                return this.demoDecimalNullableField;
            }
            set {
                this.demoDecimalNullableField = value;
            }
        }
        
        /// <remarks/>
        public bool DemoBoolean {
            get {
                return this.demoBooleanField;
            }
            set {
                this.demoBooleanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DemoBooleanNullable {
            get {
                return this.demoBooleanNullableField;
            }
            set {
                this.demoBooleanNullableField = value;
            }
        }
        
        /// <remarks/>
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public int UserAction {
            get {
                return this.userActionField;
            }
            set {
                this.userActionField = value;
            }
        }
        
        /// <remarks/>
        public IDNAME[] DemoJoins {
            get {
                return this.demoJoinsField;
            }
            set {
                this.demoJoinsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResultNoValue {
        
        private int codeField;
        
        private string[] errorsField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDemoByIdCompletedEventHandler(object sender, GetDemoByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaveDemoCompletedEventHandler(object sender, SaveDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaveDeleteCompletedEventHandler(object sender, SaveDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDemoJoinByDemoIdCompletedEventHandler(object sender, GetDemoJoinByDemoIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemoJoinByDemoIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemoJoinByDemoIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDemoByDetailIdCompletedEventHandler(object sender, GetDemoByDetailIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemoByDetailIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemoByDetailIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591